{
  "comments": [
    {
      "key": {
        "uuid": "68f5059f_90fecf80",
        "filename": "src/chromiumos/tast/local/bundles/cros/network/iwlwifi_pci_rescan.go",
        "patchSetId": 3
      },
      "lineNbr": 19,
      "author": {
        "id": 1001853
      },
      "writtenOn": "2020-02-15T02:28:59Z",
      "side": 1,
      "message": "Add a comment: \"Keep the test to reproduce issue locally.\"",
      "revId": "cd4af7dc3811bf1edd8756e9b172c335d9f21eb0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "5a11fd4e_ab917e5f",
        "filename": "src/chromiumos/tast/local/bundles/cros/network/iwlwifi_pci_rescan.go",
        "patchSetId": 3
      },
      "lineNbr": 19,
      "author": {
        "id": 1371981
      },
      "writtenOn": "2020-02-18T02:12:25Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "68f5059f_90fecf80",
      "revId": "cd4af7dc3811bf1edd8756e9b172c335d9f21eb0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "b3f186ab_f40ed11c",
        "filename": "src/chromiumos/tast/local/bundles/cros/network/iwlwifirescan/rescan.go",
        "patchSetId": 3
      },
      "lineNbr": 173,
      "author": {
        "id": 1001853
      },
      "writtenOn": "2020-02-15T02:28:59Z",
      "side": 1,
      "message": "It is out-of-the-scope of this CL.\n\nAfter restartInterface(), is it better to call GetWifiInterface() again to check if wifi is back?",
      "revId": "cd4af7dc3811bf1edd8756e9b172c335d9f21eb0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "7fee4e36_ba21b5b5",
        "filename": "src/chromiumos/tast/local/bundles/cros/network/iwlwifirescan/rescan.go",
        "patchSetId": 3
      },
      "lineNbr": 173,
      "author": {
        "id": 1371981
      },
      "writtenOn": "2020-02-18T02:12:25Z",
      "side": 1,
      "message": "For the remote test, we already have the check in later steps, so I think it might not be good to add it for now.\nFor the local test, it\u0027ll be nice to have, but as we\u0027ll only revive the local one after the recovery mechanism is provided. So I guess we might wait for that and see if we should detect the failure here or it is already covered by global health check.",
      "parentUuid": "b3f186ab_f40ed11c",
      "revId": "cd4af7dc3811bf1edd8756e9b172c335d9f21eb0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}